// https://wicg.github.io/sanitizer-api/

[
  Exposed=Window,
  SecureContext
] interface Sanitizer {
  constructor(optional SanitizerConfig sanitizerConfig = {});
  DocumentFragment sanitize((DocumentFragment or Document) input);
  Node? sanitizeFor(DOMString forElement, DOMString markup);
};

dictionary SanitizerConfig {
  sequence<DOMString> allowElements;
  sequence<DOMString> blockElements;
  sequence<DOMString> dropElements;
  record<DOMString, sequence<DOMString>> allowAttributes;
  record<DOMString, sequence<DOMString>> dropAttributes;
  boolean allowCustomElements;
};
